language: node_js

os:
  - linux
  - osx

node_js:
  - 'node'
  - 'lts/*'
  - '7'
  - '8'
cache:
  directories:
    - ~/.npm
node_js:
  - '9'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
branch: develop