language: node_js
node_js:
  - 'stable'
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  keep-history: true
  on:
    branch: develop
before_script:
  - 'yarn global add gatsby'
  - 'yarn install'
script:
  - 'yarn run test'
after_success:
  - 'yarn run deploy'
